[workspace]
dependencies_update = true
git_release_enable = false # we only need to create a git tag for one of the crates

[[package]]
name = "soldeer-core"
version_group = "soldeer"

[[package]]
name = "soldeer-commands"
version_group = "soldeer"

[[package]]
name = "soldeer"
version_group = "soldeer"
git_tag_enable = true
git_release_enable = true
