name: 💡 Feature Request
about: Suggest a feature for Soldeer
title: ''
labels: ['enhancement']
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!
        Please fill out the sections below to help us understand your request.

        Note: please search to see if an issue already exists for the feature you are requesting.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you facing that you believe this feature would solve?
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like to see.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
