//! Lockfile handling.
//!
//! The lockfile contains the resolved dependencies of a project. It is a TOML file with an array of
//! dependencies, each containing the name, version, and other information about the dependency.
//!
//! The lockfile is used to ensure that the same versions of dependencies are installed across
//! different machines. It is also used to skip the installation of dependencies that are already
//! installed.
use crate::{
    config::Dependency,
    errors::LockError,
    utils::{is_symlink, sanitize_filename},
};
use log::{debug, warn};
use serde::{Deserialize, Serialize};
use std::{
    fs,
    path::{Path, PathBuf},
};
use uuid::Uuid;

pub mod forge;

pub const SOLDEER_LOCK: &str = "soldeer.lock";

pub type Result<T> = std::result::Result<T, LockError>;

/// A trait implemented by lockfile entries to provide the install path
pub trait Integrity {
    /// Returns the install path of the dependency.
    fn install_path(&self, deps: impl AsRef<Path>) -> PathBuf;

    /// Returns the integrity checksum if relevant.
    fn integrity(&self) -> Option<&String>;
}

/// The version of the `soldeer.lock` file format.
///
/// The version is stored in the `version` key at the root of the lockfile. Lockfiles which do not
/// have that key were generated by Soldeer 0.11 or older.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, derive_more::TryFrom)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[try_from(repr)]
#[repr(u64)]
pub enum LockFileVersion {
    /// Lockfiles generated by Soldeer 0.11 and older.
    ///
    /// The unzipping behaved slightly differently in those versions, such that the integrity
    /// checksum does not match the output produced by later Soldeer versions.
    V1 = 1,

    /// The current format, almost identical to V1, except it has versioning and the integrity
    /// checksums are not compatible with the older version.
    #[default]
    V2 = 2,
}

impl From<LockFileVersion> for u64 {
    /// The number to store in the lockfile.
    fn from(value: LockFileVersion) -> Self {
        value as Self
    }
}

impl LockFileVersion {
    /// Whether the lockfile predates the archive extraction change of Soldeer 0.12.
    ///
    /// For such lockfiles, a failed integrity check of an HTTP dependency is expected, because the
    /// checksum was computed from a different on-disk layout.
    pub fn is_legacy(self) -> bool {
        self == Self::V1
    }
}

/// A lock entry for a git dependency.
#[derive(Debug, Clone, PartialEq, Eq, Hash, bon::Builder)]
#[builder(on(String, into))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[non_exhaustive]
pub struct GitLockEntry {
    /// The name of the dependency.
    pub name: String,

    /// The version (this corresponds to the version requirement of the dependency).
    pub version: String,

    /// The git url of the dependency.
    pub git: String,

    /// The resolved git commit hash.
    pub rev: String,
}

impl Integrity for GitLockEntry {
    /// Returns the install path of the dependency.
    ///
    /// The directory does not need to exist. Since the lock entry contains the version,
    /// the install path can be calculated without needing to check the actual directory.
    fn install_path(&self, deps: impl AsRef<Path>) -> PathBuf {
        format_install_path(&self.name, &self.version, deps)
    }

    /// There is no integrity checksum for git lock entries
    fn integrity(&self) -> Option<&String> {
        None
    }
}

/// A lock entry for an HTTP dependency.
#[derive(Debug, Clone, PartialEq, Eq, Hash, bon::Builder)]
#[builder(on(String, into))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[non_exhaustive]
pub struct HttpLockEntry {
    /// The name of the dependency.
    pub name: String,

    /// The resolved version of the dependency (not necessarily matches the version requirement of
    /// the dependency).
    ///
    /// If the version req is a semver range, then this will be the exact version that was
    /// resolved.
    pub version: String,

    /// The URL from where the dependency was downloaded.
    pub url: String,

    /// The checksum of the downloaded zip file.
    pub checksum: String,

    /// The integrity hash of the downloaded zip file after extraction.
    pub integrity: String,
}

impl Integrity for HttpLockEntry {
    /// Returns the install path of the dependency.
    ///
    /// The directory does not need to exist. Since the lock entry contains the version,
    /// the install path can be calculated without needing to check the actual directory.
    fn install_path(&self, deps: impl AsRef<Path>) -> PathBuf {
        format_install_path(&self.name, &self.version, deps)
    }

    /// Returns the integrity checksum
    fn integrity(&self) -> Option<&String> {
        Some(&self.integrity)
    }
}

/// A lock entry for a private dependency.
///
/// The link is not stored in the lockfile as it must be fetched from the registry with a valid
/// token before each download.
#[derive(Debug, Clone, PartialEq, Eq, Hash, bon::Builder)]
#[builder(on(String, into))]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[non_exhaustive]
pub struct PrivateLockEntry {
    /// The name of the dependency.
    pub name: String,

    /// The resolved version of the dependency (not necessarily matches the version requirement of
    /// the dependency).
    ///
    /// If the version req is a semver range, then this will be the exact version that was
    /// resolved.
    pub version: String,

    /// The checksum of the downloaded zip file.
    pub checksum: String,

    /// The integrity hash of the downloaded zip file after extraction.
    pub integrity: String,
}

impl Integrity for PrivateLockEntry {
    /// Returns the install path of the dependency.
    ///
    /// The directory does not need to exist. Since the lock entry contains the version,
    /// the install path can be calculated without needing to check the actual directory.
    fn install_path(&self, deps: impl AsRef<Path>) -> PathBuf {
        format_install_path(&self.name, &self.version, deps)
    }

    /// Returns the integrity checksum
    fn integrity(&self) -> Option<&String> {
        Some(&self.integrity)
    }
}

/// A lock entry for a dependency.
///
/// A builder should be used to create the underlying [`HttpLockEntry`] or [`GitLockEntry`] and then
/// converted into this type with `.into()`.
///
/// # Examples
///
/// ```
/// # use soldeer_core::lock::{LockEntry, HttpLockEntry};
/// let dep: LockEntry = HttpLockEntry::builder()
///     .name("my-dep")
///     .version("1.2.3")
///     .url("https://...")
///     .checksum("dead")
///     .integrity("beef")
///     .build()
///     .into();
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "lowercase"))]
#[non_exhaustive]
pub enum LockEntry {
    /// A lock entry for an HTTP dependency.
    Http(HttpLockEntry),

    /// A lock entry for a git dependency.
    Git(GitLockEntry),

    /// A lock entry for a git dependency.
    Private(PrivateLockEntry),
}

/// A TOML representation of a lock entry, which merges all fields from the two variants of
/// [`LockEntry`].
///
/// This is used to serialize and deserialize lock entries to and from TOML. All fields which are
/// not present in both variants are optional.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub struct TomlLockEntry {
    pub name: String,
    pub version: String,
    pub git: Option<String>,
    pub url: Option<String>,
    pub rev: Option<String>,
    pub checksum: Option<String>,
    pub integrity: Option<String>,
}

impl From<LockEntry> for TomlLockEntry {
    /// Convert a [`LockEntry`] into a [`TomlLockEntry`].
    fn from(value: LockEntry) -> Self {
        match value {
            LockEntry::Http(lock) => Self {
                name: lock.name,
                version: lock.version,
                git: None,
                url: Some(lock.url),
                rev: None,
                checksum: Some(lock.checksum),
                integrity: Some(lock.integrity),
            },
            LockEntry::Git(lock) => Self {
                name: lock.name,
                version: lock.version,
                git: Some(lock.git),
                url: None,
                rev: Some(lock.rev),
                checksum: None,
                integrity: None,
            },
            LockEntry::Private(lock) => Self {
                name: lock.name,
                version: lock.version,
                git: None,
                url: None,
                rev: None,
                checksum: Some(lock.checksum),
                integrity: Some(lock.integrity),
            },
        }
    }
}

impl TryFrom<TomlLockEntry> for LockEntry {
    type Error = LockError;

    /// Convert a [`TomlLockEntry`] into a [`LockEntry`] if possible.
    fn try_from(value: TomlLockEntry) -> std::result::Result<Self, Self::Error> {
        match (value.url, value.git) {
            (None, None) => Ok(PrivateLockEntry::builder()
                .name(&value.name)
                .version(value.version)
                .checksum(value.checksum.ok_or(LockError::MissingField {
                    field: "checksum".to_string(),
                    dep: value.name.clone(),
                })?)
                .integrity(value.integrity.ok_or(LockError::MissingField {
                    field: "integrity".to_string(),
                    dep: value.name,
                })?)
                .build()
                .into()),
            (None, Some(git)) => {
                Ok(GitLockEntry::builder()
                    .name(&value.name)
                    .version(value.version)
                    .git(git)
                    .rev(value.rev.ok_or(LockError::MissingField {
                        field: "rev".to_string(),
                        dep: value.name,
                    })?)
                    .build()
                    .into())
            }
            (Some(url), None) => Ok(HttpLockEntry::builder()
                .name(&value.name)
                .version(value.version)
                .url(url)
                .checksum(value.checksum.ok_or(LockError::MissingField {
                    field: "checksum".to_string(),
                    dep: value.name.clone(),
                })?)
                .integrity(value.integrity.ok_or(LockError::MissingField {
                    field: "integrity".to_string(),
                    dep: value.name,
                })?)
                .build()
                .into()),
            (Some(_), Some(_)) => Err(LockError::InvalidLockEntry),
        }
    }
}

impl LockEntry {
    /// The name of the dependency.
    pub fn name(&self) -> &str {
        match self {
            Self::Git(lock) => &lock.name,
            Self::Http(lock) => &lock.name,
            Self::Private(lock) => &lock.name,
        }
    }

    /// The version of the dependency.
    pub fn version(&self) -> &str {
        match self {
            Self::Git(lock) => &lock.version,
            Self::Http(lock) => &lock.version,
            Self::Private(lock) => &lock.version,
        }
    }

    /// The install path of the dependency.
    pub fn install_path(&self, deps: impl AsRef<Path>) -> PathBuf {
        match self {
            Self::Git(lock) => lock.install_path(deps),
            Self::Http(lock) => lock.install_path(deps),
            Self::Private(lock) => lock.install_path(deps),
        }
    }

    /// Get the underlying [`HttpLockEntry`] if this is an HTTP lock entry.
    pub fn as_http(&self) -> Option<&HttpLockEntry> {
        if let Self::Http(l) = self { Some(l) } else { None }
    }

    /// Get the underlying [`GitLockEntry`] if this is a git lock entry.
    pub fn as_git(&self) -> Option<&GitLockEntry> {
        if let Self::Git(l) = self { Some(l) } else { None }
    }

    /// Get the underlying [`PrivateLockEntry`] if this is a private package lock entry.
    pub fn as_private(&self) -> Option<&PrivateLockEntry> {
        if let Self::Private(l) = self { Some(l) } else { None }
    }
}

impl From<HttpLockEntry> for LockEntry {
    /// Wrap an [`HttpLockEntry`] in a [`LockEntry`].
    fn from(value: HttpLockEntry) -> Self {
        Self::Http(value)
    }
}

impl From<GitLockEntry> for LockEntry {
    /// Wrap a [`GitLockEntry`] in a [`LockEntry`].
    fn from(value: GitLockEntry) -> Self {
        Self::Git(value)
    }
}

impl From<PrivateLockEntry> for LockEntry {
    /// Wrap a [`PrivateLockEntry`] in a [`LockEntry`].
    fn from(value: PrivateLockEntry) -> Self {
        Self::Private(value)
    }
}

/// A parsed TOML lock file.
///
/// The lockfile is a table with one entry `dependencies` containing an array of [`TomlLockEntry`]s.
#[derive(Serialize, Deserialize, Debug, Clone, Default, PartialEq, Eq, Hash)]
struct LockFileParsed {
    version: Option<u64>,
    dependencies: Vec<TomlLockEntry>,
}

/// The result of reading and parsing a lock file.
///
/// The [`TomlLockEntry`]s are converted into [`LockEntry`]s. A copy of the text contents of
/// the lockfile is provided for diffing purposes.
#[derive(Debug, Clone, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct LockFile {
    /// The format version of the lockfile.
    pub version: LockFileVersion,

    /// The version number found in the lockfile, when it is newer than any format this build of
    /// Soldeer knows about.
    ///
    /// The lockfile is then read as the most recent known format, which is not guaranteed to be
    /// correct. Callers should tell the user to upgrade Soldeer.
    pub unknown_version: Option<u64>,

    /// The parsed lock entries.
    pub entries: Vec<LockEntry>,

    /// The raw contents of the lockfile.
    pub raw: String,
}

/// Read a lockfile from disk.
pub fn read_lockfile(path: impl AsRef<Path>) -> Result<LockFile> {
    if is_symlink(&path)? {
        return Err(LockError::IOError(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "soldeer.lock must not be a symlink",
        )));
    }
    if !path.as_ref().exists() {
        debug!(path:? = path.as_ref(); "lockfile does not exist");
        return Ok(LockFile::default());
    }
    let contents = fs::read_to_string(&path)?;

    let data: LockFileParsed = toml_edit::de::from_str(&contents).inspect_err(|err| {
        warn!(path:? = path.as_ref(), err:%; "error while parsing soldeer.lock TOML contents");
    })?;
    let entries =
        data.dependencies.into_iter().map(TryInto::try_into).collect::<Result<Vec<LockEntry>>>()?;
    // if missing, we use V1
    // if provided and we don't know about this version, we record it to emit a warning later
    // and we use the latest as fallback
    let mut unknown_version = None;
    let version = data.version.map_or(LockFileVersion::V1, |v| {
        LockFileVersion::try_from(v).unwrap_or_else(|_| {
            warn!(path:? = path.as_ref(), version = v; "unknown lockfile format version");
            unknown_version = Some(v);
            LockFileVersion::default()
        })
    });
    Ok(LockFile { version, unknown_version, entries, raw: contents })
}

/// Generate the contents of a lockfile from a list of lock entries.
///
/// The entries do not need to be sorted, they will be sorted by name.
///
/// Pass the default [`LockFileVersion`] unless the goal is to preserve the format version of an
/// existing lockfile whose entries were not all recomputed.
pub fn generate_lockfile_contents(mut entries: Vec<LockEntry>, version: LockFileVersion) -> String {
    entries.sort_unstable_by(|a, b| a.name().cmp(b.name()));
    let data = LockFileParsed {
        version: Some(version.into()),
        dependencies: entries.into_iter().map(Into::into).collect(),
    };
    toml_edit::ser::to_string_pretty(&data).expect("Lock entries should be serializable")
}

/// Whether two sets of lock entries only differ by their integrity checksums.
///
/// This is used to detect when a migration is needed from a V1 lockfile to the most recent version.
pub fn only_integrity_differs(old: &[LockEntry], new: &[LockEntry]) -> bool {
    fn without_integrity(entries: &[LockEntry]) -> Vec<TomlLockEntry> {
        let mut entries: Vec<TomlLockEntry> = entries.iter().cloned().map(Into::into).collect();
        for entry in &mut entries {
            entry.integrity = None;
        }
        entries.sort_unstable_by(|a, b| a.name.cmp(&b.name));
        entries
    }
    without_integrity(old) == without_integrity(new)
}

/// Write contents to a lockfile without following symlinks.
///
/// To ensure the path is not modified to be a symlink again after the check,
/// the contents are written to a temporary file in the same folder and then the
/// file is renamed to overwrite the final location.
///
/// # Errors
/// If the `path` is a symlink, an `IOError` is returned.
pub fn write_lockfile(contents: &str, path: impl AsRef<Path>) -> Result<()> {
    let path = path.as_ref();
    if is_symlink(path)? {
        return Err(LockError::IOError(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "soldeer.lock must not be a symlink",
        )));
    }
    replace_file(contents, path)?;
    debug!(path:? = path; "lockfile modified");
    Ok(())
}

/// Add a lock entry to a lockfile.
///
/// If an entry with the same name already exists, it will be replaced.
/// The entries are sorted by name before being written back to the file.
pub fn add_to_lockfile(entry: LockEntry, path: impl AsRef<Path>) -> Result<()> {
    let mut lockfile = read_lockfile(&path)?;
    if let Some(index) = lockfile.entries.iter().position(|e| e.name() == entry.name()) {
        debug!(name = entry.name(); "replacing existing lockfile entry");
        let _ = std::mem::replace(&mut lockfile.entries[index], entry);
    } else {
        debug!(name = entry.name(); "adding new lockfile entry");
        lockfile.entries.push(entry);
    }
    // the other entries were not recomputed, so the format version of the file is preserved
    let new_contents = generate_lockfile_contents(lockfile.entries, lockfile.version);
    write_lockfile(&new_contents, &path)
}

/// Remove a lock entry from a lockfile, matching on the name.
///
/// If the entry is the last entry in the lockfile, the lockfile will be removed.
pub fn remove_lock(dependency: &Dependency, path: impl AsRef<Path>) -> Result<()> {
    let lockfile = read_lockfile(&path)?;
    let version = lockfile.version;

    let entries: Vec<_> = lockfile
        .entries
        .into_iter()
        .filter_map(|e| if e.name() != dependency.name() { Some(e.into()) } else { None })
        .collect();

    if entries.is_empty() {
        // remove lock file if there are no deps left
        debug!(path:? = path.as_ref(); "no remaining lockfile entry, deleting file");
        let _ = fs::remove_file(&path);
        return Ok(());
    }

    // the remaining entries were not recomputed, so the format version of the file is preserved
    let file_contents = toml_edit::ser::to_string_pretty(&LockFileParsed {
        version: Some(version.into()),
        dependencies: entries,
    })?;

    // replace contents of lockfile with new contents
    write_lockfile(&file_contents, &path)
}

/// Format the install path of a dependency.
///
/// The folder name is sanitized to remove disallowed characters.
pub fn format_install_path(name: &str, version: &str, deps: impl AsRef<Path>) -> PathBuf {
    deps.as_ref().join(sanitize_filename(&format!("{name}-{version}")))
}

/// Replace a file with the given contents, via a temporary file in the same
/// folder.
///
/// The rename is atomic and replaces any potential symlink at `path`.
fn replace_file(contents: &str, path: &Path) -> Result<()> {
    let Some(filename) = path.file_name() else {
        return Err(LockError::IOError(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "lockfile path must point to a file",
        )));
    };
    let mut tmp_filename = filename.to_os_string();
    tmp_filename.push(format!(".{}.tmp", Uuid::new_v4()));
    let tmp_path = path.with_file_name(tmp_filename);
    let res = fs::write(&tmp_path, contents).and_then(|()| fs::rename(&tmp_path, path));
    if let Err(e) = res {
        let _ = fs::remove_file(&tmp_path);
        return Err(e.into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use testdir::testdir;

    #[test]
    fn test_toml_to_lock_entry_conversion_http() {
        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: None,
            url: Some("https://example.com/zip.zip".to_string()),
            rev: None,
            checksum: Some("123456".to_string()),
            integrity: Some("beef".to_string()),
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(entry.is_ok(), "{entry:?}");
        let entry = entry.unwrap();
        assert_eq!(entry.name(), "test");
        assert_eq!(entry.version(), "1.0.0");
        let http = entry.as_http().unwrap();
        assert_eq!(http.url, "https://example.com/zip.zip");
        assert_eq!(http.checksum, "123456");
        assert_eq!(http.integrity, "beef");
    }

    #[test]
    fn test_toml_to_lock_entry_conversion_git() {
        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: Some("git@github.com:test/test.git".to_string()),
            url: None,
            rev: Some("123456".to_string()),
            checksum: None,
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(entry.is_ok(), "{entry:?}");
        let entry = entry.unwrap();
        assert_eq!(entry.name(), "test");
        assert_eq!(entry.version(), "1.0.0");
        let git = entry.as_git().unwrap();
        assert_eq!(git.git, "git@github.com:test/test.git");
        assert_eq!(git.rev, "123456");
    }

    #[test]
    fn test_toml_lock_entry_bad_http() {
        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: None,
            url: Some("https://example.com/zip.zip".to_string()),
            rev: None,
            checksum: None,
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(
            matches!(entry, Err(LockError::MissingField { ref field, dep: _ }) if field == "checksum"),
            "{entry:?}"
        );

        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: None,
            url: Some("https://example.com/zip.zip".to_string()),
            rev: None,
            checksum: Some("123456".to_string()),
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(
            matches!(entry, Err(LockError::MissingField { ref field, dep: _ }) if field == "integrity"),
            "{entry:?}"
        );
    }

    #[test]
    fn test_toml_lock_entry_bad_private() {
        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: None,
            url: None,
            rev: None,
            checksum: None,
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(
            matches!(entry, Err(LockError::MissingField { ref field, dep: _ }) if field == "checksum"),
            "{entry:?}"
        );
    }

    #[test]
    fn test_toml_lock_entry_bad_git() {
        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: Some("git@github.com:test/test.git".to_string()),
            url: Some("https://example.com/zip.zip".to_string()),
            rev: None,
            checksum: None,
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(matches!(entry, Err(LockError::InvalidLockEntry)), "{entry:?}");

        let toml_entry = TomlLockEntry {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            git: Some("git@github.com:test/test.git".to_string()),
            url: None,
            rev: None,
            checksum: None,
            integrity: None,
        };
        let entry: Result<LockEntry> = toml_entry.try_into();
        assert!(
            matches!(entry, Err(LockError::MissingField { ref field, dep: _ }) if field == "rev"),
            "{entry:?}"
        );
    }

    #[test]
    fn test_read_lockfile() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        // an invalid entry invalidates the whole lockfile
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"

[[dependencies]]
name = "test2"
version = "1.0.0"
url = "https://example.com/zip.zip"
checksum = "123456"
integrity = "beef"

[[dependencies]]
name = "test3"
version = "1.0.0"
"#;
        fs::write(&file_path, content).unwrap();
        let res = read_lockfile(&file_path);
        assert!(matches!(res, Err(LockError::MissingField { .. })));
    }

    #[test]
    fn test_generate_lockfile_content() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"version = 2

[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"

[[dependencies]]
name = "test2"
version = "1.0.0"
url = "https://example.com/zip.zip"
checksum = "123456"
integrity = "beef"
"#;
        fs::write(&file_path, content).unwrap();
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.version, LockFileVersion::V2);
        let new_content = generate_lockfile_contents(lockfile.entries, LockFileVersion::default());
        assert_eq!(new_content, content);
    }

    #[test]
    fn test_read_lockfile_version() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"
"#;
        // a lockfile without a version key was generated by soldeer v0.11 or older
        fs::write(&file_path, content).unwrap();
        assert_eq!(read_lockfile(&file_path).unwrap().version, LockFileVersion::V1);

        fs::write(
            &file_path,
            format!(
                "version = 1

{content}"
            ),
        )
        .unwrap();
        assert_eq!(read_lockfile(&file_path).unwrap().version, LockFileVersion::V1);

        fs::write(
            &file_path,
            format!(
                "version = 2

{content}"
            ),
        )
        .unwrap();
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.version, LockFileVersion::V2);
        assert_eq!(lockfile.unknown_version, None);

        // a version we don't know about is read as the most recent known format, and reported so
        // that the user can be told to upgrade
        fs::write(
            &file_path,
            format!(
                "version = 3

{content}"
            ),
        )
        .unwrap();
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.version, LockFileVersion::V2);
        assert_eq!(lockfile.unknown_version, Some(3));
    }

    #[test]
    fn test_add_to_lockfile_preserves_version() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        // legacy lockfile, the other entries keep checksums which were not recomputed
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"
"#;
        fs::write(&file_path, content).unwrap();
        let entry: LockEntry = HttpLockEntry::builder()
            .name("test2")
            .version("1.0.0")
            .url("https://example.com/zip.zip")
            .checksum("123456")
            .integrity("beef")
            .build()
            .into();
        add_to_lockfile(entry, &file_path).unwrap();
        assert_eq!(read_lockfile(&file_path).unwrap().version, LockFileVersion::V1);
    }

    #[test]
    fn test_only_integrity_differs() {
        let http = |version: &str, checksum: &str, integrity: &str| -> LockEntry {
            HttpLockEntry::builder()
                .name("test")
                .version(version)
                .url("https://example.com/zip.zip")
                .checksum(checksum)
                .integrity(integrity)
                .build()
                .into()
        };
        let git: LockEntry = GitLockEntry::builder()
            .name("test2")
            .version("1.0.0")
            .git("git@github.com:test/test.git")
            .rev("123456")
            .build()
            .into();
        let old = [http("1.0.0", "123456", "beef"), git.clone()];

        // same entries, in a different order
        assert!(only_integrity_differs(&old, &[git.clone(), http("1.0.0", "123456", "beef")]));
        // only the integrity checksum changed
        assert!(only_integrity_differs(&old, &[http("1.0.0", "123456", "dead"), git.clone()]));
        // the archive checksum changed
        assert!(!only_integrity_differs(&old, &[http("1.0.0", "abcdef", "beef"), git.clone()]));
        // the version changed
        assert!(!only_integrity_differs(&old, &[http("1.1.0", "123456", "beef"), git.clone()]));
        // a dependency was removed
        assert!(!only_integrity_differs(&old, &[git]));
    }

    #[test]
    fn test_add_to_lockfile() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"
"#;
        fs::write(&file_path, content).unwrap();
        let entry: LockEntry = HttpLockEntry::builder()
            .name("test2")
            .version("1.0.0")
            .url("https://example.com/zip.zip")
            .checksum("123456")
            .integrity("beef")
            .build()
            .into();
        let res = add_to_lockfile(entry.clone(), &file_path);
        assert!(res.is_ok(), "{res:?}");
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.entries.len(), 2);
        assert_eq!(lockfile.entries[1], entry);
    }

    #[test]
    fn test_replace_in_lockfile() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"
"#;
        fs::write(&file_path, content).unwrap();
        let entry: LockEntry = HttpLockEntry::builder()
            .name("test")
            .version("2.0.0")
            .url("https://example.com/zip.zip")
            .checksum("123456")
            .integrity("beef")
            .build()
            .into();
        let res = add_to_lockfile(entry.clone(), &file_path);
        assert!(res.is_ok(), "{res:?}");
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.entries.len(), 1);
        assert_eq!(lockfile.entries[0], entry);
    }

    #[test]
    fn test_remove_lock() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"

[[dependencies]]
name = "test2"
version = "1.0.0"
url = "https://example.com/zip.zip"
checksum = "123456"
integrity = "beef"
"#;
        fs::write(&file_path, content).unwrap();
        let dep = Dependency::from_name_version("test2~2.0.0", None, None).unwrap();
        let res = remove_lock(&dep, &file_path);
        assert!(res.is_ok(), "{res:?}");
        let lockfile = read_lockfile(&file_path).unwrap();
        assert_eq!(lockfile.entries.len(), 1);
        assert_eq!(lockfile.entries[0].name(), "test");
    }

    #[test]
    fn test_remove_lock_empty() {
        let dir = testdir!();
        let file_path = dir.join(SOLDEER_LOCK);
        let content = r#"[[dependencies]]
name = "test"
version = "1.0.0"
git = "git@github.com:test/test.git"
rev = "123456"
"#;
        fs::write(&file_path, content).unwrap();
        let dep = Dependency::from_name_version("test~1.0.0", None, None).unwrap();
        let res = remove_lock(&dep, &file_path);
        assert!(res.is_ok(), "{res:?}");
        assert!(!file_path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn test_lockfile_symlink_is_rejected() {
        use std::os::unix::fs::symlink;

        let dir = testdir!();
        let target = dir.join("trusted.lock");
        let link = dir.join(SOLDEER_LOCK);
        fs::write(&target, "trusted").unwrap();
        symlink(&target, &link).unwrap();

        assert!(matches!(read_lockfile(&link), Err(LockError::IOError(_))));
        let entry: LockEntry = HttpLockEntry::builder()
            .name("test")
            .version("1.0.0")
            .url("https://example.com/zip.zip")
            .checksum("123456")
            .integrity("beef")
            .build()
            .into();
        assert!(matches!(add_to_lockfile(entry, &link), Err(LockError::IOError(_))));
        assert_eq!(fs::read_to_string(target).unwrap(), "trusted");
    }

    #[cfg(unix)]
    #[test]
    fn test_write_lockfile_does_not_follow_symlink() {
        use std::os::unix::fs::symlink;

        let dir = testdir!();
        let target = dir.join("trusted.lock");
        let link = dir.join(SOLDEER_LOCK);
        fs::write(&target, "trusted").unwrap();
        symlink(&target, &link).unwrap();

        // simulates losing the check-to-write race: the symlink is replaced, not written through
        replace_file("attacker", &link).unwrap();

        assert_eq!(fs::read_to_string(&target).unwrap(), "trusted");
        assert!(!fs::symlink_metadata(&link).unwrap().file_type().is_symlink());
    }

    #[test]
    fn test_write_lockfile_leaves_no_temp_file() {
        let dir = testdir!();
        let path = dir.join(SOLDEER_LOCK);
        write_lockfile("[[dependencies]]\n", &path).unwrap();

        assert_eq!(fs::read_to_string(&path).unwrap(), "[[dependencies]]\n");
        let leftovers: Vec<_> = fs::read_dir(&dir)
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .filter(|n| n != SOLDEER_LOCK)
            .collect();
        assert!(leftovers.is_empty(), "leftover files: {leftovers:?}");
    }
}
